---

- name: Task 1 - Setup users
  gather_facts: false
  become: true
  hosts: deployment
  tasks:
    - name: Setup docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Setup groups
      ansible.builtin.group:
        name: '{{ item.name }}'
        gid: '{{ item.gid }}'
        state: present
      loop:
        - { name: 'admins', gid: 2026 }
        - { name: 'developers', gid: 2027 }

    - name: Add developers and admins to docker
      ansible.builtin.user:
        name: '{{ item }}'
        groups: docker
        append: true
        state: present
      loop:
        - admins
        - developers

    - name: Allow passwordless sudo for admins
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/admins_nopasswd
        state: present
        create: true
        mode: '0440'
        line: '%admins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Setup users
      ansible.builtin.user:
        name: '{{ item.name }}'
        state: present
        groups:
          - '{{ item.group }}'
      loop:
        - { name: 'adm1', group: 'admins' }
        - { name: 'dev1', group: 'developers' }

    - name: Setup SSH keys
      ansible.posix.authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('ansible.builtin.file', playbook_dir + '/pubkeys/' ~ item ~ '_key.pub') }}"
        manage_dir: true
      loop:
        - adm1
        - dev1

- name: Task 2 - Install Docker
  gather_facts: true
  become: true
  hosts: deployment
  vars:
    dpkg_arch: '{{ "amd64" if ansible_facts["architecture"] == "x86_64" else ansible_facts["architecture"] }}'
  tasks:
    - name: Refresh apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - curl
          - ca-certificates
          - acl
        state: present

    - name: Create Docker GPG key directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository to apt sources
      ansible.builtin.apt_repository:
        repo: >
          deb
          [arch={{ dpkg_arch }}
          signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_facts["distribution_release"] }}
          stable
        state: present
        filename: docker

    - name: Refresh apt after adding docker
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker and Docker Compose
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Configure daemon.json with registries
      ansible.builtin.copy:
        content: "{{ lookup('ansible.builtin.file', playbook_dir + '/docker/daemon.json') }}"
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Allow developers and admins to use docker without sudo
      ansible.posix.acl:
        path: /var/run/docker.sock
        entity: '{{ item }}'
        etype: group
        permissions: rw
        state: present
      loop:
        - admins
        - developers

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        daemon_reload: true

- name: Task 3 - Install payload on deployment hosts
  gather_facts: false
  become: true
  hosts: deployment

- name: Task 4 - Start monitoring
  gather_facts: false
  become: false
  hosts: monitoring
